services:
  agent:
    build:
      context: ./src/SmartFlow.AgentService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=smartflow_memory
      - VECTOR_SIZE=512
      - EMBEDDING_MODEL=sentence-transformers/distiluse-base-multilingual-cased-v2
    volumes:
      - ./src/SmartFlow.AgentService:/app
    restart: always

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:      
  qdrant_data:
